### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by ErfanMahmoudi** [MajidAlinejad/Nozha-rtl-Dashboard#1]
Hi Majid.
I realize Drawer not responsive , also in some of resolution entire project completely massed up.
And when clicked on notification it's not responsive too.  
[Responsive Problems.zip](https://github.com/MajidAlinejad/Nozha-rtl-Dashboard/files/6338045/Responsive.Problems.zip)

**Comment by MajidAlinejad** [comment]
Hi erfan
I appreciate you and thanks for your time. I'm honored that you check my
code and email me about the problems.
I am looking for the solution and fixing it.
Thank you erfan.

**Comment by ErfanMahmoudi** [comment]
I using this admin panel for a university project and that is really awesome.
Thank you for your time and sharing this for us.
