### ISSUE TITLE
when i scroll down the side menu disappear and white color appear instead can we keep side menu

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [MajidAlinejad/Nozha-rtl-Dashboard#2]
when i scroll down the side menu disappear and white color appear instead can we keep side menu

![image](https://user-images.githubusercontent.com/20116830/142468991-53558322-48ed-4b87-afe9-a5a6cdb297ef.png)

**Comment by MajidAlinejad** [comment]
Thanks Ahmed Helal for reporting the issue
Its fixed now ☺️

**Comment by AhmedHelalAhmed** [comment]
Thank you so much
