### ISSUE TITLE
English number

### ISSUE THREAD

**Issue by abdullah-hamidy** [MajidAlinejad/Nozha-rtl-Dashboard#3]
I would like to write the numbers in English character while using persian or RTL version, but I can't type anything. even if I change the input type to text and language to Persian, then the numbers are written in persian character numbers ۱۲۳۴۵۶۷۸۹۰ږ
I want to write the numbers in English 1234567890 while the language is Persian

**Comment by MajidAlinejad** [comment]
Hi Abdulla
Hope you're well, first of all thank you for choosing the Nozha dashboard.
I use a copy (demo) font for dashboard and it's not official for best
experience you can use IranYekan or IranSans official font or any font that
supports Arabic/Persian language.

Best regards
Majid Alinejad
